# Generated by Django 3.2.5 on 2023-02-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='iconee',
            field=models.CharField(default='', max_length=200),
        ),
    ]
