# Generated by Django 3.2.5 on 2023-02-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0002_category_iconee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='iconee',
        ),
    ]
