# Generated by Django 3.2.5 on 2023-03-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0004_alter_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(default='', max_length=70)),
                ('company_name', models.CharField(default='', max_length=70)),
                ('subcategory_name', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=150)),
                ('icon', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(default='', max_length=100)),
                ('subcategory_id', models.CharField(default='', max_length=100)),
                ('model_year', models.CharField(default='', max_length=170)),
                ('variant', models.CharField(default='', max_length=170)),
                ('price', models.CharField(default='', max_length=170)),
                ('insured', models.CharField(default='', max_length=70)),
                ('registration_no', models.CharField(default='', max_length=170)),
                ('owner_name', models.CharField(default='', max_length=170)),
                ('mobile_no', models.CharField(default='', max_length=170)),
                ('color', models.CharField(default='', max_length=170)),
                ('fuel_type', models.CharField(default='', max_length=170)),
                ('no_of_seats', models.CharField(default='', max_length=170)),
                ('transmission_type', models.CharField(default='', max_length=170)),
                ('icon', models.ImageField(upload_to='static/')),
            ],
        ),
    ]
